# action.yml
name: Sync Repo Subdir
description: Apply changes from one repository to another, possibly involving subdirs.
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  source:  # project-name/repo-name/subdir-name
    description: source repository (and optionally directory)
    required: true
  source_branch: 
    description: Name of the source repo branch
    required: true
  target:  # project-name/repo-name/subdir-name
    description: target repository (and optionally directory)
    required: true
  target_branch: 
    description: Name of the target repo branch
  gist: # gist ID
    description: ID of the gist storing the most recent sync commit
    required: true
  github_token:
    description: Github authentication token, must have permission to push to target and create / update gist
    required: true
  testing:
    description: 'INTERNAL for testing purposes: rewrites history!'
runs:
  using: 'docker'
  image: 'Dockerfile'
