name: CI

on: pull_request

jobs:
  test-default-branch:
    uses: Axel-Naumann/sync-repo-subdir-action@pr-branch
    with:
      source: "Axel-Naumann/sync-repo-subdir-action-test-source"
      source_branch: "main"
      target: "Axel-Naumann/sync-repo-subdir-action-test-target"
      github_token: ${{ secrets.TOKEN }}
      gist: "97321608e2aa04e2a6ecbc2b68a41a99"
      testing: true
  test-same-level:
    uses: Axel-Naumann/sync-repo-subdir-action@pr-branch
    with:
      source: "Axel-Naumann/sync-repo-subdir-action-test-source"
      source_branch: "main"
      target: "Axel-Naumann/sync-repo-subdir-action-test-target"
      target_branch: "same-level"
      github_token: ${{ secrets.TOKEN }}
      gist: "97321608e2aa04e2a6ecbc2b68a41a99"
      testing: true
  test-subdir-level:
    uses: Axel-Naumann/sync-repo-subdir-action@pr-branch
    with:
      source: "Axel-Naumann/sync-repo-subdir-action-test-source/subdir"
      source_branch: "main"
      target: "Axel-Naumann/sync-repo-subdir-action-test-target"
      target_branch: "subdir-level"
      github_token: ${{ secrets.TOKEN }}
      gist: "97321608e2aa04e2a6ecbc2b68a41a99"
      testing: true
    
